# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Update when we update the profile
  # and then at 5AM UTC every day
  schedule: 
     - cron: '0 5 * * *'
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: General
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/general.svg
          token: ${{ secrets.GH_TOKEN }}
          user: TheKingOfAtlantis
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          plugin_traffic: yes
      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/achievements.svg
          token: ${{ secrets.GH_TOKEN }}
          user: TheKingOfAtlantis
          template: classic
          base: ""
          config_timezone: Europe/London
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
      - name: Contributions
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/contributions.svg
          token: ${{ secrets.GH_TOKEN }}
          user: TheKingOfAtlantis
          template: classic
          base: ""
          config_timezone: Europe/London
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/languages.svg
          token: ${{ secrets.GH_TOKEN }}
          user: TheKingOfAtlantis
          template: classic
          base: ""
          config_timezone: Europe/London
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: percentage,lines
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%
      - name: Wakatime
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/wakatime.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, editors-graphs, os, os-graphs
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_user: current
